title: Bundles Development Accelerator
description: Create and manage bundles on the commercetools platform.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-minimal
